// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dev-hyunsang/golang-jwt-redis/ent/predicate"
	"github.com/dev-hyunsang/golang-jwt-redis/ent/todo"
	"github.com/google/uuid"
)

// ToDoUpdate is the builder for updating ToDo entities.
type ToDoUpdate struct {
	config
	hooks    []Hook
	mutation *ToDoMutation
}

// Where appends a list predicates to the ToDoUpdate builder.
func (tdu *ToDoUpdate) Where(ps ...predicate.ToDo) *ToDoUpdate {
	tdu.mutation.Where(ps...)
	return tdu
}

// SetTodoUUID sets the "todo_uuid" field.
func (tdu *ToDoUpdate) SetTodoUUID(u uuid.UUID) *ToDoUpdate {
	tdu.mutation.SetTodoUUID(u)
	return tdu
}

// SetNillableTodoUUID sets the "todo_uuid" field if the given value is not nil.
func (tdu *ToDoUpdate) SetNillableTodoUUID(u *uuid.UUID) *ToDoUpdate {
	if u != nil {
		tdu.SetTodoUUID(*u)
	}
	return tdu
}

// SetUserUUID sets the "user_uuid" field.
func (tdu *ToDoUpdate) SetUserUUID(u uuid.UUID) *ToDoUpdate {
	tdu.mutation.SetUserUUID(u)
	return tdu
}

// SetNillableUserUUID sets the "user_uuid" field if the given value is not nil.
func (tdu *ToDoUpdate) SetNillableUserUUID(u *uuid.UUID) *ToDoUpdate {
	if u != nil {
		tdu.SetUserUUID(*u)
	}
	return tdu
}

// SetTodoTitle sets the "todo_title" field.
func (tdu *ToDoUpdate) SetTodoTitle(s string) *ToDoUpdate {
	tdu.mutation.SetTodoTitle(s)
	return tdu
}

// SetTodoContext sets the "todo_context" field.
func (tdu *ToDoUpdate) SetTodoContext(s string) *ToDoUpdate {
	tdu.mutation.SetTodoContext(s)
	return tdu
}

// SetUpdatedAt sets the "updated_at" field.
func (tdu *ToDoUpdate) SetUpdatedAt(t time.Time) *ToDoUpdate {
	tdu.mutation.SetUpdatedAt(t)
	return tdu
}

// SetCratedAt sets the "crated_at" field.
func (tdu *ToDoUpdate) SetCratedAt(t time.Time) *ToDoUpdate {
	tdu.mutation.SetCratedAt(t)
	return tdu
}

// Mutation returns the ToDoMutation object of the builder.
func (tdu *ToDoUpdate) Mutation() *ToDoMutation {
	return tdu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tdu *ToDoUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tdu.hooks) == 0 {
		affected, err = tdu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ToDoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tdu.mutation = mutation
			affected, err = tdu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tdu.hooks) - 1; i >= 0; i-- {
			if tdu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tdu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tdu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (tdu *ToDoUpdate) SaveX(ctx context.Context) int {
	affected, err := tdu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tdu *ToDoUpdate) Exec(ctx context.Context) error {
	_, err := tdu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tdu *ToDoUpdate) ExecX(ctx context.Context) {
	if err := tdu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tdu *ToDoUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   todo.Table,
			Columns: todo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: todo.FieldID,
			},
		},
	}
	if ps := tdu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tdu.mutation.TodoUUID(); ok {
		_spec.SetField(todo.FieldTodoUUID, field.TypeUUID, value)
	}
	if value, ok := tdu.mutation.UserUUID(); ok {
		_spec.SetField(todo.FieldUserUUID, field.TypeUUID, value)
	}
	if value, ok := tdu.mutation.TodoTitle(); ok {
		_spec.SetField(todo.FieldTodoTitle, field.TypeString, value)
	}
	if value, ok := tdu.mutation.TodoContext(); ok {
		_spec.SetField(todo.FieldTodoContext, field.TypeString, value)
	}
	if value, ok := tdu.mutation.UpdatedAt(); ok {
		_spec.SetField(todo.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tdu.mutation.CratedAt(); ok {
		_spec.SetField(todo.FieldCratedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tdu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{todo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// ToDoUpdateOne is the builder for updating a single ToDo entity.
type ToDoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ToDoMutation
}

// SetTodoUUID sets the "todo_uuid" field.
func (tduo *ToDoUpdateOne) SetTodoUUID(u uuid.UUID) *ToDoUpdateOne {
	tduo.mutation.SetTodoUUID(u)
	return tduo
}

// SetNillableTodoUUID sets the "todo_uuid" field if the given value is not nil.
func (tduo *ToDoUpdateOne) SetNillableTodoUUID(u *uuid.UUID) *ToDoUpdateOne {
	if u != nil {
		tduo.SetTodoUUID(*u)
	}
	return tduo
}

// SetUserUUID sets the "user_uuid" field.
func (tduo *ToDoUpdateOne) SetUserUUID(u uuid.UUID) *ToDoUpdateOne {
	tduo.mutation.SetUserUUID(u)
	return tduo
}

// SetNillableUserUUID sets the "user_uuid" field if the given value is not nil.
func (tduo *ToDoUpdateOne) SetNillableUserUUID(u *uuid.UUID) *ToDoUpdateOne {
	if u != nil {
		tduo.SetUserUUID(*u)
	}
	return tduo
}

// SetTodoTitle sets the "todo_title" field.
func (tduo *ToDoUpdateOne) SetTodoTitle(s string) *ToDoUpdateOne {
	tduo.mutation.SetTodoTitle(s)
	return tduo
}

// SetTodoContext sets the "todo_context" field.
func (tduo *ToDoUpdateOne) SetTodoContext(s string) *ToDoUpdateOne {
	tduo.mutation.SetTodoContext(s)
	return tduo
}

// SetUpdatedAt sets the "updated_at" field.
func (tduo *ToDoUpdateOne) SetUpdatedAt(t time.Time) *ToDoUpdateOne {
	tduo.mutation.SetUpdatedAt(t)
	return tduo
}

// SetCratedAt sets the "crated_at" field.
func (tduo *ToDoUpdateOne) SetCratedAt(t time.Time) *ToDoUpdateOne {
	tduo.mutation.SetCratedAt(t)
	return tduo
}

// Mutation returns the ToDoMutation object of the builder.
func (tduo *ToDoUpdateOne) Mutation() *ToDoMutation {
	return tduo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tduo *ToDoUpdateOne) Select(field string, fields ...string) *ToDoUpdateOne {
	tduo.fields = append([]string{field}, fields...)
	return tduo
}

// Save executes the query and returns the updated ToDo entity.
func (tduo *ToDoUpdateOne) Save(ctx context.Context) (*ToDo, error) {
	var (
		err  error
		node *ToDo
	)
	if len(tduo.hooks) == 0 {
		node, err = tduo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ToDoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tduo.mutation = mutation
			node, err = tduo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tduo.hooks) - 1; i >= 0; i-- {
			if tduo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tduo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, tduo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*ToDo)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from ToDoMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (tduo *ToDoUpdateOne) SaveX(ctx context.Context) *ToDo {
	node, err := tduo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tduo *ToDoUpdateOne) Exec(ctx context.Context) error {
	_, err := tduo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tduo *ToDoUpdateOne) ExecX(ctx context.Context) {
	if err := tduo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tduo *ToDoUpdateOne) sqlSave(ctx context.Context) (_node *ToDo, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   todo.Table,
			Columns: todo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: todo.FieldID,
			},
		},
	}
	id, ok := tduo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ToDo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tduo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, todo.FieldID)
		for _, f := range fields {
			if !todo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != todo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tduo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tduo.mutation.TodoUUID(); ok {
		_spec.SetField(todo.FieldTodoUUID, field.TypeUUID, value)
	}
	if value, ok := tduo.mutation.UserUUID(); ok {
		_spec.SetField(todo.FieldUserUUID, field.TypeUUID, value)
	}
	if value, ok := tduo.mutation.TodoTitle(); ok {
		_spec.SetField(todo.FieldTodoTitle, field.TypeString, value)
	}
	if value, ok := tduo.mutation.TodoContext(); ok {
		_spec.SetField(todo.FieldTodoContext, field.TypeString, value)
	}
	if value, ok := tduo.mutation.UpdatedAt(); ok {
		_spec.SetField(todo.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tduo.mutation.CratedAt(); ok {
		_spec.SetField(todo.FieldCratedAt, field.TypeTime, value)
	}
	_node = &ToDo{config: tduo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tduo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{todo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
