// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ToDo is the predicate function for todo builders.
type ToDo func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
